name: Release Obsidian plugin - Markdown Timeline

on:
  push:
    tags:
      # release when tag is in the format of X.Y.Z
      - "*"

env:
  PLUGIN_NAME: markdown-timeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # Read the release notes
          notes=""
          if [ -f release-notes.md ]; then
            notes="$(cat release-notes.md)"
          fi
          
          gh release create "$tag" \
            --title="$tag" \
            --notes="$notes" \
            main.js manifest.json styles.css

      - name: Upload files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          gh release upload "$tag" \
            main.js \
            manifest.json \
            styles.css 